title: Cass Zhao
url: "casszhao.github.io/cass/"
baseurl: "/cass"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.sheffield.ac.uk/dcs/people/research-staff/cass-zhixue-zhao"
footer_text: "Lecturer @ShefNLP"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/cass"
 - name: "Publications"
   link: "publications"
 - name: "Contact"
   link: "contact"
 - name: "Beyond Research"
   link: "NotResearch"

plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jemoji
